### ISSUE TITLE
Problems with tests

### ISSUE THREAD

**Issue by jmichel7** [kalmarek/AbstractPermutations.jl#12]
I registered a new version of `PermGroups` using  `AbstractPermutations`.  

First, I did not any more pass *my* tests since you have defined a method

`Base.show(::IO,::MIME"text/plain",::AbstractPerm)`

Since I did not define such a method for my `Perm`, this was hijacking in many cases my own `show` for `Perm`. I fixed the problem by defining such a method, but I think you should not define such a method.

I don't pass your tests for the last two reasons below:
  - You assumed that a malformed permutation raises an `ArgumentError`. Since I raised another error type, your test failed and made all the other tests fail (not execute). Since I don't mind, I made my functions return `ArgumentError`  but I think you should fix your tests so that at least they continue even if another error type is returned.
  - I introduced a checking constructor, but, as I always do, I made  `check`  a keyword argument and not an optional argument. I will not change this since I think it is much clearer what it means when you encounter in some code `Perm(v;check=false)` versus `Perm(v,false)`.
  - In your tests the constructor is called in the form `Perm{T}(v)`. I did not define such a constructor, since it is not necessary. If you want to convert the argument you may always do `Perm(T.(v))`. (I have a constructor `Perm{T}(i1,...,in)` for a cycle but that is a different circumstance).

**Comment by kalmarek** [comment]
* You are free to adjust how your permutations are printed according to your taste. (I will be modifying io part soon anyway to make use of more extended features such as display limiting, etc. Contributions/ideas are welcome!
* the ArgumentError on invalid images is non-compulsory as we have discussed this; moreover you stated that you don't even validate the images constructor, hence I introduced this commit: https://github.com/kalmarek/AbstractPermutations.jl/commit/6b959b8a9bec3af8062132dda737eb7d8aaef7e5
Now, since you actually started validating the images is this commit even necessary?
* indeed `Perm` constructor with keyword argument might be another option; however then we need to put some consideration into its name (which is not the case for standard argument). I have two suggestions here: `APerm(images; check=true)` or `APerm(images; validate=true)`, with slight preference for the latter actually. Any preference/suggestion from you?
* do you refer to those tests: https://github.com/kalmarek/AbstractPermutations.jl/blob/main/test/abstract_perm_API.jl ? Then I don't see where `Perm{T}` is called, only `P` which is the argument.

**Comment by jmichel7** [comment]
To answer your various points

> You are free to adjust how your permutations are printed according to your taste

My printing is basically like yours. The difference is that I print the type `Perm{T}:`  when `T` is not `Int16` (the default type for my `Perm`s) and the type has not been already printed (which can be determined by the io property `:typeinfo`).

> Now, since you actually started validating the images is this commit even necessary?

It is not any more necessary.

> I have two suggestions here: APerm(images; check=true) or APerm(images; validate=true), with slight preference for the latter actually. Any preference/suggestion from you?

Both are slightly imprecise. `validate_input` would be precise but is cumbersome. I prefer `check` which is short and clear enough (and you probably agreed when you called your optional argument `check` in the source code of your constructor).

>  I don't see where Perm{T} is called, only P which is the argument.

Line 6 of `arithmetic.jl` you have `return typeof(σ)(img, false)` where `typeof(σ)` expands to `Perm{T}`. You should use instead the argument `P` to `abstract_perm_interface_test`. You would have found this if you had tried to test my package.

By the way, your README is not as clear as it could be. You write

`abstract_perm_interface_test(ExamplePerms.Perm)`

where according to what you write above it should be 

`abstract_perm_interface_test(ExamplePerms.APerm)`

I think it would even be better if you wrote `APerms` instead of `ExamplePerms`.

**Comment by kalmarek** [comment]
* in #13 I added more advanced printing methods; feel free to suggest more improvements there
* ok I'll remove it then, `ArgumentError`s will be thrown.
* `APerm(images::AbstractVector; check::Bool=true)` it will be then.
* Well then `PermGroups.Perm{T}` doesn't implement the interface, does it? The interface requires a constructor based on type. As I said before I will not "shove anything down your throat" (just to quote you :). You need to implement, check and run it yourself.
* The point of the snippet given in README is that it can be pasted directly and run in any julia session that has access to `AbstractPermutations`. I'll remove the reference to `APerm`.

**Comment by jmichel7** [comment]
> in https://github.com/kalmarek/AbstractPermutations.jl/pull/13 I added more advanced printing methods; feel free to suggest more improvements there

I am not sure to have followed correctly your logic, but:

my permutation pass the round-trip test:  `p==eval(Meta.parse(repr(p)))`. For that, `print(p) ` prints the style
`perm"(1,2)(3,4)"` while I think you print the non-parseable "(1,2)(3,4)" (which should be printed only if `:limit=true' which is the most reliable indicator that one is in the REPL, Ijulia or pluto).

> Well then PermGroups.Perm{T} doesn't implement the interface, does it? The interface requires a constructor based on type. As I said before I will not "shove anything down your throat" (just to quote you :). You need to implement, check and run it yourself.

What you say is not clear to me. We have `Perm{T}<;Perm`for any `T`. So `Perm` is as well the type of permutations a `Perm{T}` is. And `Perm`*is* the argument to `abstract_perm_interface_test`.  I did not implement a constructor `Perm{T}`since it seems to me pointless (thus harmful). I could write

`Perm{T}(v;check) where T=Perm(v;check)`

but that is even more silly. Something like

`Perm{T}(v;check) where T=Perm(T.(v);check)`

seems more reasonable. But what is the point? This is completely unneeded. So please, be kind and explain/justify a bit your design for my enlightenment.

**Comment by kalmarek** [comment]
#13 decoupled show/printing from the interface; You can continue to use whatever `show` for your permutations that suits your taste.

Every concrete subtype of `AbstractPermutation` needs to implement a constructor of specified semantics. This sentence seems clear enough. Maybe what is not clear to you is that `Perm` is **not** a concrete type. Your constructor for `Perm` just happens to return `Perm{T}` for some `T`.

But regardless: maybe such constructor is not needed from your perspective, but to preserve the type of permutations given by our users while providing uniform construction method it is indeed necessary. That is unless you propose something else that works also for permutations which encode additional information in their type (except `T`).

**Comment by jmichel7** [comment]
I have had problems since I used `AbstractPermutations`. Errors sometimes with `deepcopy`, in general `deepcopy` much
slower. I think this is due to the definition of `Base.deepcopy_internal`  in your code. I solved it by defining `Base.deepcopy` in my code (it was not overloaded before)  but is what you did OK?

**Comment by kalmarek** [comment]
What is the error? Note that one should not overload `Base.deepcopy` directly.

Indeed there was an error in the implementation that did not preserve the identical permutations. Have a look at #16

**Comment by jmichel7** [comment]
Why do you overload `Base.deepcopy_internal` ? This makes it impossible to avoid your code. But at least you could make your code so that I could avoid the slowdown that your method ` _deepcopy`  brings to me (now you renamed it `_copy_by_images`). Since you define `Base.copy` by `_deepcopy`, in the code you wrote for  `Base.deepcopy_internal` you should just call `copy` instead of `_deppcopy` and then the copy will go through my fast code.

**Comment by kalmarek** [comment]
@jmichel7 feel free to make a PR on top of #16 with the changes that you deem fit.

**Comment by jmichel7** [comment]
well, I just ask to change line 155 of `abstract_perm.jl` from

        `stackdict[p] = _copy_by_images(p)`

to 
       
        `stackdict[p] = copy(p)`

It should be faster for you to do this than for me to prepare a PR.

**Comment by kalmarek** [comment]
such change would not be correct

**Comment by kalmarek** [comment]
because `copy` is not the same as `deepcopy`. the former may resolve to the latter but not the other way around. please consult the docstrings of both methods

**Comment by jmichel7** [comment]
My reasoning is very simple:  your code for `copy(AbstractPerm)` *is* `_copy_by_images`. So for you replacing 
 `_copy_by_images` by `copy` changes nothing. But for me who has my own method for copy which is faster than your method (since I just copy the data field) this makes an improvement.

Speaking about `correct` I think it is not correct for you to overload an internal non-exported and undocumented function `deepcopy_internal`.

**Comment by kalmarek** [comment]
It changes plenty, since by default `copy` may not create an object fully independent from its argument, while `deepcopy` must.

as for overloading `deepcopy_internal`: all those words could be spared had you consulted the docstring of `deepcopy`.

**Comment by jmichel7** [comment]
You did not answer me: 

why did you deemed necessary to overload `deepcopy_internal`.

**Comment by kalmarek** [comment]
so that this method doesn't have to be overloaded multiple times (for every subtype), especially that it is not trivial to get it right.

But reading between your verses: Are you suggesting the removal of the definition and relying on the default mechanisms of julia instead?

**Comment by jmichel7** [comment]
Yes, I would prefer if you rely on the default mechanism of Julia. This is the only one of your definitions that a subtype of `AbstractPermutations` cannot easily overload. The default mechanism of Julia applied to my permutations is quite a bit faster than going through your code.

**Comment by kalmarek** [comment]
#19 has been merged, all things should be resolved now.

**Comment by jmichel7** [comment]
I just registered a version, 0.2.15, which passes all tests of `AbstractPermutations` 0.3.0
